

# ===============================
# Kitty Main Config
# ===============================

# Include theme file
include current-theme.conf
confirm_os_window_close 0
# Shell
shell fish -l
shell tmux


background_opacity 0.75

# Fonts
font_family FiraCode Nerd Font
bold_font auto
italic_font auto
font_size 20.0

# Cursor
cursor_shape block
cursor_blinking yes
cursor_color #FF79C6

# Tabs
enable_tab_bar yes
active_tab_background #282A36
inactive_tab_background #44475A
tab_bar_style powerline
show_tab_index yes

# Scrolling
scrollback_lines 10000
map ctrl+shift+up scroll_line_up
map ctrl+shift+down scroll_line_down

# Window
window_padding_width 0
#background_opacity 1.0
resize_in_steps no
# Keybindings (external)
include keybindings.conf

# Misc
allow_remote_control yes
shell_integration yes


