set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

unbind C-b 
set -g prefix M-a 
bind-key M-a send-prefix

set -g base-index 1
setw -g pane-base-index 1

unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U 
bind l select-pane -R 

unbind n 
bind n new-window

unbind r 
bind r source-file "~/.config/tmux/tmux.conf"


set -g status on

# Set colors to match 1984 theme
set -g status-bg "#282A36"   # 1984 background
set -g status-fg "#F8F8F2"   # 1984 foreground

# Remove all default info
set -g status-left ""
set -g status-right ""
set -g status-interval 0       # don’t refresh anything

# Optional: hide pane numbers in status bar
set -g display-panes-time 0
